name: Release & Publish to NPM

on: workflow_dispatch

jobs:
  publish-npm:
    name: "Publish: npm Registry"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org"

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install packages
        run: bun ci

      - name: Initialize git user
        run: |
          git config --global user.email "nick@nicholasradford.com"
          git config --global user.name "shiba Release"

      - name: Log diff
        run: |
          git status
          git diff

      - name: Run release
        run: NODE_AUTH_TOKEN="" bun release --ci --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
